name: "Cached Nightly Build"
description: "Runs the rust nightly build with sccache"

inputs:
  rust-components:
    description: Required components by toolchain
    required: true

  aws-access-key-id:
    description: Access key id for sccache
    required: true

  aws-secret-access-key:
    description: Secret access key for sccache
    required: true

  aws-region:
    description: Region to run the Bucket
    required: true

  s3-bucket:
    description: Bucket for S3 sccache
    required: true

runs:
  using: "composite"
  steps:
    - name: Install nightly toolchain
      uses: ./.github/actions/nightly-build
      with:
        rust-components: ${{ inputs.rust-components }}

    - name: Install sccache (ubuntu-latest)
      shell: bash
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-${{ env.SCCACHE_VERSION }}-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "${{ env.LINK }}/${{ env.SCCACHE_VERSION }}/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        export SCCACHE_REGION="${{ inputs.aws-region }}"
        export SCCACHE_BUCKET="${{ inputs.s3-bucket }}"
        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
        export SCCACHE_CACHE_SIZE="20G"
        sccache --show-stats

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
