name: Project Build

on:
  pull_request:
    branches:
    - develop
    - master
    - cicd*
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
    - develop
    - master
    - cicd*
jobs:
  code-coverate:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: ./.github/actions/nightly-build

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'
